[package]
name = "vrcapi_proxy"
version = "1.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/yu256/Rocket/", rev = "2468764015c2bdfc1be5a03c43dc3e98bde4f436", features = ["json"] }
anyhow = "*"
ureq = { version = "*", default-features=false, features = ["json", "native-tls"] }
serde = "*"
base64 = "*"
serde_json = "*"
dirs-2 = "*"
tokio-tungstenite = { version = "*", features = ["native-tls"] }
futures = "*"
native-tls = "*"
trie-match = "*"
