[package]
name = "vrcapi_proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "=0.5.0-rc.3"
anyhow = "1.0.72"
reqwest = { version = "0.11.18", features = ["json"] }
serde = "1.0.181"
base64 = "0.21.2"
serde_json = "1.0.104"
dirs-2 = "3.0.1"
uuid = { version = "1.4.1", features = ["v4"] }