[package]
name = "vrcapi_proxy"
version = "1.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/yu256/Rocket/", rev = "2468764015c2bdfc1be5a03c43dc3e98bde4f436", features = ["json"] }
anyhow = "1.0.72"
ureq = { version = "*", features = ["json"] }
serde = "1.0.181"
base64 = "0.21.2"
serde_json = "1.0.104"
dirs-2 = "3.0.1"
tokio-tungstenite = { version = "*", features = ["native-tls"] }
futures = "*"