[package]
name = "vrcapi_proxy"
version = "1.0.6-beta3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "=0.5.0-rc.3", features = ["json"] }
anyhow = "1.0.72"
ureq = { version = "*", features = ["json"] }
serde = "1.0.181"
base64 = "0.21.2"
serde_json = "1.0.104"
dirs-2 = "3.0.1"
tokio-tungstenite = { version = "*", features = ["native-tls"] }
futures = "*"